# Generated by Django 2.2 on 2020-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_body',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
