# Generated by Django 2.2 on 2020-06-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200616_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_body',
            field=models.TextField(),
        ),
    ]
